# Generated by Django 5.2.4 on 2025-07-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsesDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('Purchase Staff', 'Purchase Staff'), ('Helper', 'Helper'), ('Supervisor', 'Supervisor'), ('Mechanic', 'Mechanic'), ('Owner', 'Owner'), ('Senior Mechanic', 'Senior Mechanic')], default='Helper', max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('JoinDate', models.CharField(blank=True, max_length=15, null=True)),
                ('ResignDate', models.CharField(blank=True, max_length=15, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive'), ('On Leave', 'On Leave')], default='InActive', max_length=20)),
                ('BasicSalary', models.IntegerField(blank=True, null=True)),
                ('BankAccount', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_prf/')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Owner.shopdb')),
            ],
        ),
    ]
