# Generated by Django 5.2.4 on 2025-07-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_remindersdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='remindersdb',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending', max_length=20, null=True),
        ),
    ]
