# Generated by Django 5.2.4 on 2025-07-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ItemCode', models.CharField(blank=True, max_length=100, null=True)),
                ('ItemName', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Value', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='Out of Stock', max_length=20)),
                ('PurchaseStatus', models.TextField(blank=True, default=' ', null=True)),
                ('salesStatus', models.TextField(blank=True, default=' ', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stok_prf/')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Owner.shopdb')),
            ],
        ),
    ]
