# Generated by Django 5.2.4 on 2025-07-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
        ('Spare_Purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editeed_details', models.TextField(blank=True, null=True)),
                ('customernotes', models.TextField(blank=True, null=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Owner.usesdb')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(blank=True, choices=[('Service', 'Service'), ('Repair', 'Repair'), ('Inspection', 'Inspection'), ('Custom', 'Custom Work')], max_length=20, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('work_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending', max_length=20, null=True)),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.usesdb')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Supervisor.customerdb')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardPartsDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('JobCart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Supervisor.jobcarddb')),
                ('part_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Spare_Purchase.stockdb')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=50, null=True)),
                ('petrol_level', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supervisor.customerdb')),
            ],
        ),
        migrations.AddField(
            model_name='jobcarddb',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Supervisor.vehicledb'),
        ),
    ]
