# Generated by Django 5.2.4 on 2025-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddb',
            name='TotalPayent',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=10, null=True),
        ),
    ]
