# Generated by Django 5.2.4 on 2025-07-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0002_jobcarddb_totalpayent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddb',
            name='paymentStatus',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending', max_length=20, null=True),
        ),
    ]
