# Generated by Django 5.2.4 on 2025-07-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
        ('Supervisor', '0003_jobcarddb_paymentstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='absent', max_length=20, null=True)),
                ('morning_check_in', models.TimeField(blank=True, null=True)),
                ('morning_check_out', models.TimeField(blank=True, null=True)),
                ('morning_remarks', models.TextField(blank=True, null=True)),
                ('afternoon_status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='absent', max_length=20, null=True)),
                ('afternoon_check_in', models.TimeField(blank=True, null=True)),
                ('afternoon_check_out', models.TimeField(blank=True, null=True)),
                ('afternoon_remarks', models.TextField(blank=True, null=True)),
                ('total_working_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('day_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='absent', max_length=20)),
                ('daily_remarks', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Owner.usesdb')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Owner.usesdb')),
            ],
        ),
    ]
