# Generated by Django 5.2.4 on 2025-07-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0004_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdb',
            name='editeed_details',
        ),
        migrations.AddField(
            model_name='jobcarddb',
            name='editeed_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
