# Generated by Django 5.2.4 on 2025-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
