# Generated by Django 5.2.4 on 2025-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0005_remove_customerdb_editeed_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddb',
            name='paydPayent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobcarddb',
            name='TotalPayent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
