# Generated by Django 5.2.4 on 2025-07-22 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
        ('Supervisor', '0005_attendance_late_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total_hours',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Owner.usesdb'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
