# Generated by Django 5.2.4 on 2025-07-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0006_jobcarddb_paydpayent_alter_jobcarddb_totalpayent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddb',
            name='PaymentMethod',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Cash', 'Cash'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Bank Transfe', 'Bank Transfe')], default='UPI', max_length=20, null=True),
        ),
    ]
