# Generated by Django 5.2.4 on 2025-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0007_jobcarddb_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddb',
            name='PaymentNotes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
