# Generated by Django 5.2.4 on 2025-07-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0008_jobcarddb_paymentnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcarddb',
            name='Paymentdonebynote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
