# Generated by Django 5.2.4 on 2025-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0009_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_check_in',
            field=models.TimeField(blank=True, default='14:00', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_check_out',
            field=models.TimeField(blank=True, default='17:00', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_check_in',
            field=models.TimeField(blank=True, default='08:30', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_check_out',
            field=models.TimeField(blank=True, default='13:00', null=True),
        ),
    ]
