# Generated by Django 5.2.4 on 2025-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0010_alter_attendance_afternoon_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='afternoon_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('overtime', 'Overtime')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='day_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('overtime', 'Overtime')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('overtime', 'Overtime')], default='absent', max_length=20),
        ),
    ]
