# Generated by Django 5.2.4 on 2025-07-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supervisor', '0009_jobcarddb_paymentdonebynote'),
        ('Supervisor', '0011_alter_attendance_afternoon_status_and_more'),
    ]

    operations = [
    ]
